### ISSUE TITLE
Using Kubernetes v1.20.0, getting "unexpected error getting claim reference: selfLink was empty, can't make reference"

### ISSUE THREAD

**Issue by nealman13** [kubernetes-sigs/nfs-subdir-external-provisioner#25]
Using Kubernetes v1.20.0

Attempting to create pvc's, they all remain in "pending" status

Doing a kubectl logs nfs-client-provisioner gives this:

I1210 14:42:01.396466       1 leaderelection.go:194] successfully acquired lease default/fuseim.pri-ifs
I1210 14:42:01.396534       1 controller.go:631] Starting provisioner controller fuseim.pri/ifs_nfs-client-provisioner-64b7476494-p4fcm_dcfca333-3af5-11eb-8248-5aed4ceb7af7!
I1210 14:42:01.496922       1 controller.go:680] Started provisioner controller fuseim.pri/ifs_nfs-client-provisioner-64b7476494-p4fcm_dcfca333-3af5-11eb-8248-5aed4ceb7af7!
I1210 14:42:01.497152       1 controller.go:987] provision "default/pvc1" class "managed-nfs-storage": started
I1210 14:42:01.497157       1 controller.go:987] provision "default/test-claim" class "managed-nfs-storage": started
E1210 14:42:01.500487       1 controller.go:1004] provision "default/pvc1" class "managed-nfs-storage": unexpected error getting claim reference: selfLink was empty, can't make reference
E1210 14:42:01.500502       1 controller.go:1004] provision "default/test-claim" class "managed-nfs-storage": unexpected error getting claim reference: selfLink was empty, can't make reference

selfLink has been disabled in v1.20.0
https://github.com/kubernetes/enhancements/issues/1164

**Comment by fangedhex** [comment]
I can confirm that I have this problem too on my new cluster using Kubernetes v1.20 with those same logs/errors when creating a test pvc.

**Comment by nealman13** [comment]
Current workaround is to edit /etc/kubernetes/manifests/kube-apiserver.yaml

Under here:
spec:
  containers:
  - command:
    - kube-apiserver


Add this line:
    - --feature-gates=RemoveSelfLink=false

The do this:
kubectl apply -f /etc/kubernetes/manifests/kube-apiserver.yaml
kubectl apply -f /etc/kubernetes/manifests/kube-apiserver.yaml

(I had to do it twice to get it to work)

**Comment by petermicuch** [comment]
Yep, exactly the same issue. In k8s 1.20 they have removed selfLink as per [release notes](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md).

Adding selfLink manually does not help, as that is removed by API server immediatelly.

**Comment by fangedhex** [comment]
I used @nealman13's workaround until a fix is made and it works now. Thanks !

**Comment by petermicuch** [comment]
Just to add to what @nealman13 provided. Before first leader election log, there is this error:
```
E1210 15:41:30.047572       1 event.go:259] Could not construct reference to: '&v1.Endpoints{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"nfss", SelfLink:"", UID:"75df6842-e437-4604-9034-2d4d932373be", ResourceVersion:"19431", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:63743203519, loc:((nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string{"control-plane.alpha.kubernetes.io/leader":"{\"holderIdentity\"eb-af59-dac986fde3f6\",\"leaseDurationSeconds\":15,\"acquireTime\":\"2020-12-10T15:41:30Z\",\"renewTime\":\"2020-12-10T15:41:30Z\",\"leaderTransitions\":1}"}, OwnerReference)(nil), Finalizers:[]string(nil), ClusterName:""}, Subsets:[]v1.EndpointSubset(nil)}' due to: 'selfLink was empty, can't make reference'. Will not report event: 'Normal' 'Le2d51-3afe-11eb-af59-dac986fde3f6 became leader'
I1210 15:41:30.047754       1 leaderelection.go:194] successfully acquired lease default/fuseim.pri-ifs
```

**Comment by petermicuch** [comment]
I think the problem is in using the old client-go by this [replace](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/blob/920c708218be0fadbc50fea4d25b42c279fefe21/go.mod#L28), but I am not 100% sure if that is the only legacy we pull here.

Same problem was discussed in [#94660](https://github.com/kubernetes/kubernetes/issues/94660) and [this](https://github.com/kubernetes/kubernetes/issues/94660#issuecomment-689887045) was suggested solution.

**Comment by james-d-elliott** [comment]
Just a note about `/etc/kubernetes/manifests/kube-apiserver.yaml`. When running the control-plane as an in-cluster service you should not need to apply changes to this file ever. As soon as you save the change to disk the apiserver pods will detect it and should conduct a Rolling Update. You can watch the progress with `watch kubectl get pods --namespace kube-system`. You can confirm the behavior after deleting the provisioner pod and letting it restart.

**Comment by iming0319** [comment]
The workaround will no longer work after 1.20.
"selfLink is a URL representing this object. Populated by the system. Read-only. DEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."

**Comment by zaneclaes** [comment]
The "fix" now causes a `CrashLoopBackoff` on `kube-apiserver`, per @iming0319 .
Is there any way to get NFS working with Kubernetes 1.20.1?

**Comment by yonatankahana** [comment]
> The "fix" now causes a `CrashLoopBackoff` on `kube-apiserver`, per @iming0319 .
> Is there any way to get NFS working with Kubernetes 1.20.1?

what "fix" you tried? have you tried #26 ?

**Comment by zaneclaes** [comment]
> have you tried #26 ?

It does not appear to be merged. So, no, I have not pulled and built that PR (yet).

**Comment by groundhog2k** [comment]
@zaneclaes: I created a fork of nfs-subdir-external-provisioner, merged the PR from @petermicuch and adapted the action workflow to create an automated build + multi-arch. docker image - try v3.2.0 of https://hub.docker.com/r/groundhog2k/nfs-subdir-external-provisioner/tags?page=1&ordering=last_updated - It should work for Kubernetes >= V1.20.x.

**Comment by olcayseker** [comment]
I have tried your fork with feature-gate trick but pvc stucks in pending state. Kubernetes version is 1.20.0 log message is;

Waiting for a volume to be created, either by external provisioner "cluster.local/nfs-client-provisioner" or manually created by system administrator

**Comment by groundhog2k** [comment]
@olcayseker: I don't know which fork you mean, but if you are talking about https://github.com/groundhog2k/nfs-subdir-external-provisioner, i can say it's definetly working. I tested in on ARM64 and AMD64/x86 with and without feature-gate switch and using it since 15 days on my mixed-arch. cluster without any problems. Have you looked at the logs of the nfs-provisioner pod when PVC is in pending state?

**Comment by jsafrane** [comment]
I'm trying to fix this in #32, I'd appreciate some more thorough testing.
/assign

**Comment by petermicuch** [comment]
@jsafrane it is already fixed with #26, it works also with k8s 1.20.x I've tested it myself. We are only waiting for review from maintainers of this project for quite some time to get it merged.

**Comment by jsafrane** [comment]
Awesome, I'll delete my PR.

**Comment by petermicuch** [comment]
@kmova or @jackielii - would it be possible to create new release now with the fix #26 merged to main so that this issues could be closed? There are still new and new people seeking official released fix?

**Comment by chief93** [comment]
For `v1.20.2` issue still presents (trying `nfs-client-provisioner`). Seems like a lot of Kubernetes software (MetalLB, NFS provisioners and so on) are based on this (`selfLink`) functionality. It must be some discussion between Kubernetes core developers and 3rd-party Kuberentes software developers for asap solvind of such important issues, that affects a lot of projects

**Comment by petermicuch** [comment]
@chief93 the code in this repo works fine even with k8s v 1.20.2. The problem is, there was no new official docker image published yet, which I thought would be done with build updates provided by @kmova. So for now you either have to build your own or use one build by others like [here](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/pull/26#issuecomment-743745469).

**Comment by timmilesdw** [comment]
Built code from master branch to a docker image
https://hub.docker.com/r/timmiles/nfs-subdir-external-provisioner
docker pull timmiles/nfs-subdir-external-provisioner

**Comment by kmova** [comment]
Can you also please try this image generated and published from this repo. 
`gcr.io/k8s-staging-sig-storage/nfs-subdir-external-provisioner:canary`

**Comment by petermicuch** [comment]
Hi @kmova I have tested with your image `gcr.io/k8s-staging-sig-storage/nfs-subdir-external-provisioner:canary` the basic scenario create/delete pvc and check that pv was created/archived (tested with postgres DB). This work on k8s version `Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0"`.

So could we now get official new release :-) ?

**Comment by leandrofrs** [comment]
@petermicuch and @kmova Im at `Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64` and I tried with the image you said `gcr.io/k8s-staging-sig-storage/nfs-subdir-external-provisioner:canary`. The PV is created and it's Bound with the PVC but it doesn't write on it. At least I tried with jenkins and postgresql charts and the pods won't get ready.

**Comment by petermicuch** [comment]
@leandrofrs I believe that might be different issue. Provisioner is responsible to bound PVC to PV and create respective sub-directory structure on the referenced NFS server (can you see that this was done?). In my case postgress was able to create DB and work with it. In your case you might need to set correct permission for your NFS share. I might be wrong, but that is my assumption.

**Comment by petermicuch** [comment]
@nealman13 could you please also test with #49 now merged. It would be good to close this issue if you do not observe described problem anymore with image gcr.io/k8s-staging-sig-storage/nfs-subdir-external-provisioner:v4.0.0

**Comment by huntersan9** [comment]
Just tested with gcr.io/k8s-staging-sig-storage/nfs-subdir-external-provisioner:v4.0.0 installed from helm 4.0.2 and am able to create a new volume on nfs just fine

**Comment by nealman13** [comment]
I built my own container and tested it.  I confirm that it worked for me in my K8s 1.20 cluster.  All the pvcs were created and bound and everything worked for me.

**Comment by caihy05** [comment]
@nealman13 感谢，添加apiserver配置成功解决问题
- --feature-gates=RemoveSelfLink=false

**Comment by kadirsahan** [comment]
> Current workaround is to edit /etc/kubernetes/manifests/kube-apiserver.yaml
> 
> Under here:
> 
> ```
> spec:
>   containers:
>   - command:
>     - kube-apiserver
> ```
> 
> Add this line:
> - --feature-gates=RemoveSelfLink=false
> 
> The do this:
> kubectl apply -f /etc/kubernetes/manifests/kube-apiserver.yaml
> kubectl apply -f /etc/kubernetes/manifests/kube-apiserver.yaml
> 
> (I had to do it twice to get it to work)

it worked for me without running kubectl apply command

**Comment by achernev** [comment]
I had it working with:
```
helm repo add nfs-subdir-external-provisioner https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
helm install nfs-subdir-external-provisioner nfs-subdir-external-provisioner
```
Chart version 4.0.6 and app version 4.0.1 as reported by `helm search repo nfs-subdir-external-provisioner`.

**Comment by azui007** [comment]
> Current workaround is to edit /etc/kubernetes/manifests/kube-apiserver.yaml
> 
> Under here:
> 
> ```
> spec:
>   containers:
>   - command:
>     - kube-apiserver
> ```
> 
> Add this line:
> - --feature-gates=RemoveSelfLink=false
> 
> The do this:
> kubectl apply -f /etc/kubernetes/manifests/kube-apiserver.yaml
> kubectl apply -f /etc/kubernetes/manifests/kube-apiserver.yaml
> 
> (I had to do it twice to get it to work)

it work for me ,thank you

**Comment by petermicuch** [comment]
No more workarounds please :-) - this issue was closed for a reason guys! Just use new available docker image: `gcr.io/k8s-staging-sig-storage/nfs-subdir-external-provisioner:v4.0.0` and it works fine. Do not edit kube-apiserver.yaml, there is no need to.

**Comment by cleverlzc** [comment]
the same error, trying

**Comment by abdennour** [comment]
same error 
```sh
class "nfs-client": unexpected error getting claim reference: selfLink was empty, can't make reference
```
my env:
- k8s: 1.20
- helm chart stable/nfs-client-provisioner 1.2.8 ( app versopn 3.1.0)

**Comment by petermicuch** [comment]
@abdennour - you should read the comments above. This issue is closed and there is new helm chart and new container image existing that fixed this issue. Please try to update with [helm](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/blob/master/charts/nfs-subdir-external-provisioner/README.md).

`helm repo add nfs-subdir-external-provisioner https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/`

```
:~$ helm search repo nfs
NAME                                                    CHART VERSION   APP VERSION     DESCRIPTION
nfs-subdir-external-provisioner/nfs-subdir-exte...      4.0.14          4.0.2           nfs-subdir-external-provisioner is an automatic...
```

**Comment by abdennour** [comment]
Thank you  @petermicuch 
It's working BUT I think it requires a doc for migration.
So far there are 2 steps before applying helm:

1. if you are using private/proxy registry make sure to point to the new image in gcr instead of the old one in quay.
2. delete MANUALLY 2 resources : the storageclass & the deployment

Then run helm apply

**Comment by petermicuch** [comment]
@abdennour - feel free to create PR with your migration description, I think maintainers will accept it if it adds value to the community. But please create separate feature request for that one. Thank you.

**Comment by PhillipDowney** [comment]
> @olcayseker: I don't know which fork you mean, but if you are talking about https://github.com/groundhog2k/nfs-subdir-external-provisioner, i can say it's definetly working. I tested in on ARM64 and AMD64/x86 with and without feature-gate switch and using it since 15 days on my mixed-arch. cluster without any problems. Have you looked at the logs of the nfs-provisioner pod when PVC is in pending state?

Worked for me also , Storage class definition simpler as well

**Comment by finance-dataspider** [comment]
> @zaneclaes: I created a fork of nfs-subdir-external-provisioner, merged the PR from @petermicuch and adapted the action workflow to create an automated build + multi-arch. docker image - try v3.2.0 of https://hub.docker.com/r/groundhog2k/nfs-subdir-external-provisioner/tags?page=1&ordering=last_updated - It should work for Kubernetes >= V1.20.x.

this works! thanks a lot!!!!

**Comment by ashkarstudy** [comment]
@petermicuch
Thank you. Its worked on 1.27.0

**Comment by lIlIlllllmeng** [comment]
<pre>apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubeadm.kubernetes.io/kube-apiserver.advertise-address.endpoint: 192.168.100.100:6443
  creationTimestamp: null
  labels:
    component: kube-apiserver
    tier: control-plane
  name: kube-apiserver
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-apiserver
    - --advertise-address=192.168.100.100
    - --allow-privileged=true
    - --audit-log-format=json
    - --audit-log-maxage=7
    - --audit-log-maxbackup=10
    - --audit-log-maxsize=100
    - --audit-log-path=/var/log/kubernetes/audit.log
    - --audit-policy-file=/etc/kubernetes/audit-policy.yml
    - --authorization-mode=Node,RBAC
    - --client-ca-file=/etc/kubernetes/pki/ca.crt
    - --enable-admission-plugins=NodeRestriction
    - --enable-aggregator-routing=true
    - --enable-bootstrap-token-auth=true
    - --etcd-cafile=/etc/kubernetes/pki/etcd/ca.crt
    - --etcd-certfile=/etc/kubernetes/pki/apiserver-etcd-client.crt
    - --etcd-keyfile=/etc/kubernetes/pki/apiserver-etcd-client.key
    - --etcd-servers=https://127.0.0.1:2379
    - --feature-gates=
    - --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt
    - --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key
    - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
    - --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt
    - --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key
    - --requestheader-allowed-names=front-proxy-client
    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
    - --requestheader-extra-headers-prefix=X-Remote-Extra-
    - --requestheader-group-headers=X-Remote-Group
    - --requestheader-username-headers=X-Remote-User
    - --secure-port=6443
    - --service-account-issuer=https://kubernetes.default.svc.cluster.local
    - --service-account-key-file=/etc/kubernetes/pki/sa.pub
    - --service-account-signing-key-file=/etc/kubernetes/pki/sa.key
    - --service-cluster-ip-range=10.96.0.0/22
    - --tls-cert-file=/etc/kubernetes/pki/apiserver.crt
    - --tls-private-key-file=/etc/kubernetes/pki/apiserver.key
    - --feature-gates=RemoveSelfLink=false
</pre>


The connection to the server apiserver.cluster.local:6443 was refused - did you specify the right host or port?

**Comment by devopstraining99** [comment]
> Current workaround is to edit /etc/kubernetes/manifests/kube-apiserver.yaml
> 
> Under here:
> 
> ```
> spec:
>   containers:
>   - command:
>     - kube-apiserver
> ```
> 
> Add this line: - --feature-gates=RemoveSelfLink=false
> 
> The do this: kubectl apply -f /etc/kubernetes/manifests/kube-apiserver.yaml kubectl apply -f /etc/kubernetes/manifests/kube-apiserver.yaml
> 
> (I had to do it twice to get it to work)

This solutions doesn't work in kubernetes > 1.26 

I updated the image to - gcr.io/k8s-staging-sig-storage/nfs-subdir-external-provisioner:v4.0.0

and it worked thanks to @petermicuch for the solutions

try this @lIlIlllllmeng
